### ISSUE TITLE
No RDS information

### ISSUE THREAD

**Issue by devinnasar** [TerbiumLabs/check-reserved-instances#11]
Given this config.ini:

[AWS us-east-1]
aws_access_key_id = as8hasdfiasdf
aws_secret_access_key = sd9hfsad98fhsad0fsd
region = us-east-1
rds = True

I'm getting this report:

##########################################################
##########################################################
-------
Below is the report on EC2 reserved instances:
UNUSED RESERVATION!	(1)	m3.large	All	Expires in [1090] days.
UNUSED RESERVATION!	(1)	m3.xlarge	All	Expires in [1090, 1091] days.
NOT RESERVED!	(1)	m1.medium	us-east-1c	datamart
NOT RESERVED!	(1)	t1.micro	us-east-1c	syslog
NOT RESERVED!	(1)	m3.medium	us-east-1e	management
NOT RESERVED!	(1)	m1.small	us-east-1c	files (new)
(21) running on-demand EC2 instances
(19) EC2 reservations

As you can see, no rds info is present. Can you help me out with this?

**Comment by adamstauffer** [comment]
I am able to recreate. There are some bugs in the way the config file is loaded and the values are serialized. I will most likely have a fix ready sometime this week

In the meantime, as a workaround, if you remove `rds = True` from your config file, you should receive RDS information. The default value for reporting on non-ec2 services is True, so this information should be returned automatically.

**Comment by adamstauffer** [comment]
fixed in version [0.0.6](https://github.com/TerbiumLabs/check-reserved-instances/releases/tag/0.0.6)
