### ISSUE TITLE
Authenticate with instance profile

### ISSUE THREAD

**Issue by cmclaughlin** [TerbiumLabs/check-reserved-instances#15]
If you leave aws_access_key_id and aws_secret_access_key out of the config file you'll get this error:

    Required configuration option for an AWS account (aws_access_key_id) in section "AWS account1" is not configured!

It's nice not to leave passwords on the filesystem - typically boto will authenticate with the instance profile if key and keyid are left off the connection.

**Comment by mbassett** [comment]
Removing the access key altogether would make #16 much more difficult.  You'd have to give the machine iam assumerole access and swap between accounts to query the ec2 data.  

Not impossible, just more setup work and if not done properly security risk.

**Comment by mbassett** [comment]
If you don't care about the multi account issue, you should be able to just toggle the config options to not required.

https://github.com/TerbiumLabs/check-reserved-instances/blob/master/src/check_reserved_instances/config.py#L48

just change to False on lines 48-49  and rebuild/install

**Comment by cmclaughlin** [comment]
I think that's possible with one IAM role.  These docs cover the basic idea:

http://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html
http://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_policy-examples.html

Basically, the script would still use one machine role/set of credentials.  But that role would have access to the other accounts.

**Comment by mbassett** [comment]
Yep.  The code would need to be updated to use iam assumerole in the boto section.

http://boto3.readthedocs.io/en/latest/reference/services/sts.html#STS.Client.assume_role

And be very careful when making IAM assume role policy to be extremely specific in the roles you give it access to ( that guide shows a very specific role selection so it's pretty good ) or you are exposing major security risk.

**Comment by adamstauffer** [comment]
fixed in release 0.0.7, thanks
