### ISSUE TITLE
Apply reserved instance credits across all configured AWS accounts

### ISSUE THREAD

**Issue by adamstauffer** [TerbiumLabs/check-reserved-instances#16]
For those of us who are using this with multiple accounts - currently each account is treated separately when calculating reserved capacity and comparing to running instances.

Since reservation capacity applies to all accounts if accounts are used in an organization with consolidated billing ([source](https://aws.amazon.com/premiumsupport/knowledge-center/ec2-ri-consolidated-billing/)), it would make more sense to query all accounts configured at once, get the reservations and running instances, and then do the calculations on the entire set.

For those who have multiple accounts that are not linked to an organization or not doing consolidated billing, this would lead to inaccurate results if multiple accounts are configured. So maybe this should be an additional configuration option?

**Comment by mbassett** [comment]
I was thinking about this exact same issue.  We have nonprod and prod accounts, and currently the nonprod instances are not being counted in the report.

**Comment by adamstauffer** [comment]
agree, i think for those who want to keep things separate they can run twice with different configs

fixed in 0.0.7
