### ISSUE TITLE
EC2 summary is confusing a bit

### ISSUE THREAD

**Issue by kaaxa** [TerbiumLabs/check-reserved-instances#23]
In my report I got:

(14) running on-demand EC2 VPC instances
(13) EC2 VPC reservations

but actually out of 14 instances just 5 are not reserved, so report should say something like 5 on-demand and 9 reserved instances

**Comment by adamstauffer** [comment]
Yeah those numbers reported are the totals that were detected. Agree it is confusing and should probably say "total". I believe there is another ticket about overhauling the report format entirely and likely will fix this issue too

**Comment by adamstauffer** [comment]
this should be alleviated further by #25 which will list the count of unreserved instances
