### ISSUE TITLE
Reserved Instance of regional scope not identified as used

### ISSUE THREAD

**Issue by AgDude** [TerbiumLabs/check-reserved-instances#3]
The recent reserved instances I have purchased have a scope of "region" instead of "availability zone" it seems that these are not matched with running instances, so the covered instances are showing as "not reserved".

Here is the output from the CLI which describes one of these instances. Note that there is no availability zone.
```
 {
            "ReservedInstancesId": "REMOVED",
            "OfferingType": "Partial Upfront",
            "FixedPrice": 1820.0,
            "End": "2018-02-10T13:19:54.000Z",
            "ProductDescription": "Linux/UNIX",
            "Scope": "Region",
            "UsagePrice": 0.0,
            "RecurringCharges": [
                {
                    "Amount": 0.155,
                    "Frequency": "Hourly"
                }
            ],
            "OfferingClass": "standard",
            "Start": "2017-02-10T13:19:55.193Z",
            "State": "active",
            "InstanceCount": 1,
            "CurrencyCode": "USD",
            "Duration": 31536000,
            "InstanceTenancy": "default",
            "InstanceType": "i2.xlarge"
        }
```

**Comment by sjafferali** [comment]
Not sure if this is still being actively maintained, but I implemented a fix in my forked version of this repo. Give it a try: https://github.com/sjafferali/check-reserved-instances

**Comment by AgDude** [comment]
@sjafferali  Thanks. I will try that. Would you please open a pull request with that change?

**Comment by sjafferali** [comment]
Sure thing!

**Comment by adamstauffer** [comment]
Fixed in [version 0.0.4](https://github.com/TerbiumLabs/check-reserved-instances/releases/tag/0.0.4). Thanks!

**Comment by mbassett** [comment]
Traceback (most recent call last):
  File "/usr/bin/check-reserved-instances", line 11, in <module>
    load_entry_point('check-reserved-instances==0.0.4', 'console_scripts', 'check-reserved-instances')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/check_reserved_instances/__init__.py", line 31, in cli
    results[name].append(calculate_ec2_ris(account=aws_account))
  File "/usr/lib/python2.7/site-packages/check_reserved_instances/calculate.py", line 83, in calculate_ec2_ris
    if reserved_instance['Scope'] == 'Availability Zone':
KeyError: 'Scope'

**Comment by mbassett** [comment]
fix to that is  #5

**Comment by adamstauffer** [comment]
What version of boto3/botocore are you using? The `Scope` field should always be returned. See the [Response Syntax from describe_reserved_instances here](http://boto3.readthedocs.io/en/latest/reference/services/ec2.html#EC2.Client.describe_reserved_instances).

I may need to pin the version of boto3/botocore that included the above change in setup.py

**Comment by mbassett** [comment]
boto (2.46.1)
boto3 (1.4.0)
botocore (1.4.50)

**Comment by mbassett** [comment]
upgraded my boto, and no more error
boto (2.46.1)
boto3 (1.4.4)
botocore (1.5.26)
