### ISSUE TITLE
differentiate between VPC and EC2 classic reservations/instances

### ISSUE THREAD

**Issue by mbassett** [TerbiumLabs/check-reserved-instances#6]
Script does not seem to differentiate between ec2 classic and vpc reservations

(or if it does, it's not clear in the output)

**Comment by mbassett** [comment]
This definitely should be possible.

VPC reservations have different product descriptions.

"ProductDescription": "Linux/UNIX (Amazon VPC)",
"ProductDescription": "Linux/UNIX",

**Comment by adamstauffer** [comment]
fixed in [0.0.6](https://github.com/TerbiumLabs/check-reserved-instances/releases/tag/0.0.6)
